"""
Markdown formatting module for generating structured market analysis reports
"""

import logging
from typing import Dict, List
from datetime import datetime

logger = logging.getLogger(__name__)


class MarkdownFormatter:
    """
    Formats analysis results into structured markdown reports.
    """
    
    def format_report(self, sector: str, analysis: Dict) -> str:
        """
        Format analysis into a markdown report.
        
        Args:
            sector: The sector being analyzed
            analysis: Dictionary with analysis results
        
        Returns:
            Formatted markdown report
        """
        try:
            report = self._build_markdown(sector, analysis)
            logger.info(f"Successfully formatted markdown report for {sector}")
            return report
        except Exception as e:
            logger.error(f"Error formatting markdown: {str(e)}")
            return self._build_error_report(sector, str(e))
    
    def _build_markdown(self, sector: str, analysis: Dict) -> str:
        """
        Build the markdown report structure.
        
        Args:
            sector: The sector being analyzed
            analysis: Dictionary with analysis results
        
        Returns:
            Formatted markdown string
        """
        sector_title = sector.title()
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        
        # Extract analysis components
        overview = analysis.get("overview", "No overview available")
        key_trends = analysis.get("key_trends", [])
        opportunities = analysis.get("opportunities", [])
        risks = analysis.get("risks", [])
        future_outlook = analysis.get("future_outlook", "No outlook available")
        
        # Build markdown
        md = f"""# Market Analysis: {sector_title}

**Generated:** {timestamp}

---

## Overview

{overview}

---

## Key Trends

"""
        
        # Add key trends
        if isinstance(key_trends, list):
            for trend in key_trends:
                md += f"- {trend}\n"
        else:
            md += f"{key_trends}\n"
        
        md += "\n---\n\n## Trade Opportunities\n\n"
        
        # Add opportunities
        if isinstance(opportunities, list):
            for i, opp in enumerate(opportunities, 1):
                md += f"{i}. {opp}\n"
        else:
            md += f"{opportunities}\n"
        
        md += "\n---\n\n## Risks & Challenges\n\n"
        
        # Add risks
        if isinstance(risks, list):
            for risk in risks:
                md += f"- {risk}\n"
        else:
            md += f"{risks}\n"
        
        md += "\n---\n\n## Future Outlook (2-3 Years)\n\n"
        md += f"{future_outlook}\n"
        
        md += "\n---\n\n## Recommendations\n\n"
        md += self._generate_recommendations(sector, analysis)
        
        md += "\n---\n\n*Report generated by Trade Opportunities API*\n"
        
        return md
    
    def _generate_recommendations(self, sector: str, analysis: Dict) -> str:
        """
        Generate recommendations based on analysis.
        
        Args:
            sector: The sector being analyzed
            analysis: Dictionary with analysis results
        
        Returns:
            Recommendations as markdown
        """
        recommendations = f"""### For Investors:
- Focus on sectors with strong government support and policy tailwinds
- Consider long-term growth potential in emerging technologies
- Diversify across multiple opportunities to mitigate risks

### For Entrepreneurs:
- Identify gaps in the market and develop innovative solutions
- Leverage government schemes and incentives
- Build partnerships with established players for market access

### For Businesses:
- Invest in technology and digital transformation
- Expand into high-growth segments
- Develop sustainable and compliant operations

### Key Success Factors:
- Strong regulatory compliance and governance
- Continuous innovation and adaptation
- Strategic partnerships and collaborations
- Focus on quality and customer satisfaction
"""
        return recommendations
    
    def _build_error_report(self, sector: str, error: str) -> str:
        """
        Build an error report when formatting fails.
        
        Args:
            sector: The sector being analyzed
            error: Error message
        
        Returns:
            Error report as markdown
        """
        return f"""# Market Analysis: {sector.title()}

**Status:** Error

An error occurred while generating the market analysis report:

```
{error}
```

Please try again later or contact support.
"""
